### ISSUE TITLE
TypeAhead: when all options are selected if the tap key is pressed a empty filter is added

### ISSUE THREAD

**Issue by httpete-ire** [mxenabled/mx-react-components#34] opened 2015-10-05 14:23 UTC
OS: Mac 0.11 (15A284)
Browser: Chrome  45.0.2454.101 (64-bit)

Steps to duplicate:
1. select all options
2. press tab to insert a blank tag (this can be done numerous times)  
<img width="1002" alt="screenshot 2015-10-05 15 06 50" src="https://cloud.githubusercontent.com/assets/1556430/10282514/3a28fe10-6b73-11e5-8b2c-1482b6b0b1b6.png">

I'll take a look and make a pull request if I can fix the issue :+1:

**Comment by bsbeeks** [comment] 2015-10-05 14:44
I believe this is a duplicate of #23

**Closed** 2015-10-05 18:31 UTC
